Repository jinoc-git/traduler-project, pull requests merged in 2023-09, with the labels that each got.

#38 Fix: 드래그 앤 드롭 오류 일부 수정
  src/components/plan/updatePlan/Pin.tsx
  src/components/plan/updatePlan/Pins.tsx
Labels: 🪳버그, 🚧진행중, 🖐️merge 필요

#39 ending 페이지 동행, 지도, 코멘트 추가
  src/api/pins.ts
  src/api/plans.ts
  src/components/common/invite/Invite.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/ending/EndingMap.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/pages/AddPhoto.tsx
  src/pages/AddPlan.tsx
  src/pages/Ending.tsx
  src/pages/Plan.tsx
Labels: 🌸디자인 필요, 🪳버그, 🚧진행중, 🖐️merge 필요

#41 Feat/logout
  src/assets/icons/IconAdd.tsx
  src/assets/icons/IconSignOut.tsx
  src/components/common/header/Header.tsx
  src/components/common/sideBar/SideBar.tsx
  src/index.css
  src/pages/AddPlan.tsx
  src/pages/Main.tsx
  src/pages/Plan.tsx
  tailwind.config.js
Labels: 🌸디자인 필요, 🚧진행중

#42 Feat/mainplan
  src/api/plans.ts
  src/assets/index.ts
  src/assets/main-background-default-plan-250x200.png
  src/components/common/sideBar/SideBar.tsx
  src/components/plan/listingPlan/Card.tsx
Labels: 🚧진행중, 🖐️merge 필요

#43 Feat/ending
  src/api/endingData.ts
  src/api/path.ts
  src/components/pay/TotalPay.tsx
  src/components/plan/updatePlan/Pin.tsx
  src/pages/AddPhoto.tsx
Labels: 🚧진행중, 🖐️merge 필요

#44 Refactor: 사이드바 플랜 리스트 분리
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarPlanList.tsx
  tailwind.config.js
Labels: 🌸디자인 필요, 🚧진행중

#45 Fix/side bar bookmark
  src/assets/img-traduler-logo-color-4x.png
  src/assets/index.ts
  src/components/common/header/Header.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarETC.tsx
  src/components/common/sideBar/SideBarPlanList.tsx
  src/components/common/sideBar/SideBarStatus.tsx
  src/components/main/favorite/Favorite.tsx
  src/pages/AddPlan.tsx
  src/pages/Main.tsx
  src/utils/calcDateProgress.ts
  src/utils/changeFormatDay.ts
  tailwind.config.js
Labels: 👌완성, 🌸디자인 필요, 🖐️merge 필요

#46 Feat/dutch pay
  src/api/endingData.ts
  src/api/plans.ts
  src/components/common/invite/Invite.tsx
  src/components/pay/TotalPay.tsx
  src/pages/AddPhoto.tsx
  src/pages/Ending.tsx
  src/utils/calcDutchPay.ts
  tailwind.config.js
Labels: 🚧진행중, 🖐️merge 필요

#47 Feat/ending carousel 초안
  package.json
  src/api/endingData.ts
  src/assets/icons/IconAdd.tsx
  src/assets/icons/IconCamera.tsx
  src/assets/icons/IconFavoriteDefault.tsx
  src/assets/icons/IconFavoriteSolid.tsx
  src/assets/index.ts
  src/assets/test1.png
  src/assets/test2.png
  src/assets/test3.png
  src/components/carousel/Carousel.tsx
  src/pages/Ending.tsx
  yarn.lock
Labels: 🚧진행중, 🖐️merge 필요

#49 Feat/side bar end
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarPlanList.tsx
  src/components/common/sideBar/SideBarStatus.tsx
  src/pages/AddPhoto.tsx
  tailwind.config.js
Labels: 👌완성

#50 Feat/carousel 기능 추가
  src/assets/icons/IconCamera.tsx
  src/components/carousel/Carousel.tsx
Labels: 👌완성

#52 Fix: 엔딩 데이터 추가 오류 수정
  src/api/bookMarks.ts
  src/api/commets.ts
  src/api/endingData.ts
  src/api/path.ts
  src/api/pins.ts
  src/components/carousel/Carousel.tsx
  src/components/comments/Comments.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/main/favorite/Favorite.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/updatePlan/Pin.tsx
  src/pages/AddPhoto.tsx
  src/pages/Ending.tsx
  src/utils/calcDutchPay.ts
  src/utils/updateUserProfile.ts
Labels: 🖐️merge 필요

#56 Feat/ending-css
  src/api/endingData.ts
  src/components/pay/AddPay.tsx
  src/components/pay/Pay.tsx
  src/components/pay/TotalPay.tsx
  src/pages/Main.tsx
  src/utils/calcDutchPay.ts
Labels: 👌완성

#59 Design/loading
  src/assets/index.ts
  src/assets/loader-all-color.gif
  src/components/carousel/Carousel.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/invite/UserList.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/ending/PlaceList.tsx
  src/components/loading/Loading.tsx
  src/components/plan/ending/EndingMap.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/AddPhoto.tsx
  src/pages/Plan.tsx
  src/types/import-gif.d.ts
Labels: 👌완성

#60 Feat/protect route
  src/assets/img-traduler-logo-white-4x.png
  src/assets/index.ts
  src/components/carousel/Carousel.tsx
  src/components/common/header/Header.tsx
  src/components/common/protectRoute/ProtectRoute.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarETC.tsx
  src/components/loading/Loading.tsx
  src/pages/Landing.tsx
  src/shared/Router.tsx
  src/store/sideBarStore.ts
  src/store/userStore.ts
Labels: 🚧진행중

#63 초안 Design/add photo
  src/assets/icons/IconAdd.tsx
  src/assets/icons/IconCamera.tsx
  src/assets/icons/IconChevronLeft.tsx
  src/assets/icons/IconChevronRight.tsx
  src/assets/icons/IconDeleteDefault.tsx
  src/assets/icons/IconDeleteFill.tsx
  src/assets/icons/IconFavoriteDefault.tsx
  src/assets/icons/IconFavoriteFill.tsx
  src/assets/icons/IconFavoriteSolid.tsx
  src/assets/icons/IconGridDefault.tsx
  src/assets/icons/IconMicroMenu.tsx
  src/assets/icons/IconPin.tsx
  src/assets/icons/IconSignOut.tsx
  src/assets/icons/IconSixDots.tsx
  src/assets/icons/IconUploadPicture.tsx
  src/assets/icons/IconVector.tsx
  src/assets/index.ts
  src/assets/test1.png
  src/assets/test2.png
  src/assets/test3.png
  src/components/addpicture/AddPicture.tsx
  src/components/common/invite/UserList.tsx
  src/pages/AddPhoto.tsx
Labels: 👌완성

#65 Feat/login
  src/assets/main-background-default-plan-125x101.png
  src/assets/main-background-default-plan-250x200.png
  src/components/ending/PlaceList.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/signin/SignInForm.tsx
  src/components/signup/SignUpForm.tsx
  src/pages/Main.tsx
  tailwind.config.js
Labels: 👌완성, 🖐️merge 필요

#66 Design/notfoundpage
  src/assets/index.ts
  src/components/comments/Comments.tsx
  src/components/plan/listingPlan/Card.tsx
  src/pages/Plan.tsx
Labels: 👌완성

#67 Design/btnhover
  src/api/bookMarks.ts
  src/api/plans.ts
  src/assets/icons/IconClose.tsx
  src/assets/icons/IconUserDefault.tsx
  src/components/common/header/Header.tsx
  src/components/main/favorite/Favorite.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/components/main/profile/Profile.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/components/signin/SignInForm.tsx
  src/components/signup/SignUpForm.tsx
Labels: 🌸디자인 필요, 🚧진행중

#80 Fix: 엔딩페이지 캐러셀 오류 수정
  src/components/carousel/Carousel.tsx
  src/hooks/useFlickingPlugins.ts
  src/pages/AddPhoto.tsx
Labels: 🚧진행중

#81 Design/404
  src/assets/icons/IconFavoriteList.tsx
  src/assets/icons/IconPlannedTime.tsx
  src/assets/icons/IconPreviousTime.tsx
  src/assets/img-not-found.png
  src/assets/index.ts
  src/components/404/NotFoundFull.tsx
  src/components/common/sideBar/SideBar.tsx
Labels: 👌완성

#87 Fix/format number
  src/api/pins.ts
  src/components/pay/TotalPay.tsx
  src/components/plan/Pay.tsx
  src/components/plan/PinLayout.tsx
  src/components/plan/ending/EndingPay.tsx
  src/pages/Plan.tsx
  src/utils/calcDutchPay.ts
Labels: 👌완성

#92 Design/profile css 추가
  src/assets/icons/IconCamera.tsx
  src/assets/index.ts
  src/assets/profile-default-black.svg
  src/assets/profile-default-gray.svg
  src/components/main/profile/EditProfileModal.tsx
  src/components/main/profile/Profile.tsx
Labels: 👌완성, 🪳버그, 🙏도움 !

#95 Design/signin image
  src/assets/img-login-left-photo.png
  src/components/common/header/Header.tsx
  src/components/main/profile/Profile.tsx
  src/components/signin/SignInForm.tsx
  src/components/signup/SignUpForm.tsx
  src/utils/calcDateProgress.ts
Labels: 👌완성

#108 Design:404page 이미지 수정
  src/components/notfound/NotFoundFull.tsx
  tailwind.config.js
Labels: 👌완성

#109 Fix/addplan input focus on
  src/components/addPlan/calendar/Calendar.tsx
  src/components/addPlan/postPlan/PostPlan.tsx
  src/components/common/invite/Invite.tsx
  src/components/common/nav/Nav.tsx
  src/pages/AddPlan.tsx
  src/pages/Plan.tsx
  src/store/modifyStateStore.ts
  src/types/supabase.ts
Labels: 👌완성, 🖐️merge 필요

#112 Design/responsive main
  src/components/common/nav/Nav.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/main/card/Card.tsx
  src/components/main/card/CardAddNewPlan.tsx
  src/components/main/card/CardTabMenu.tsx
  src/components/main/card/CardUserList.tsx
  src/components/main/profile/Profile.tsx
  src/index.css
  src/pages/Main.tsx
  src/types/icon.ts
  tailwind.config.js
Labels: 🚧진행중

#115 Desing:SVG 수정
  src/assets/icons/3x/index.ts
  src/assets/icons/IconAdd.tsx
  src/assets/icons/IconCamera.tsx
  src/assets/icons/IconChevronDown.tsx
  src/assets/icons/IconChevronUp.tsx
  src/assets/icons/IconComentory.tsx
  src/assets/icons/IconEditDefault.tsx
  src/components/addPlan/calendar/Calendar.tsx
  src/components/addPlan/datePage/DatePage.tsx
  src/components/common/date/EndingDate.tsx
  src/components/common/header/Header.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/sideBar/SideBarETC.tsx
  src/components/common/sideBar/SideBarPlanList.tsx
  src/components/ending/carousel/Carousel.tsx
  src/components/ending/comments/Comments.tsx
  src/components/main/card/Card.tsx
  src/components/main/card/CardAddNewPlan.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/pages/AddPhoto.tsx
  src/pages/Main.tsx
Labels: 👌완성

#121 font 적용 수정
  src/assets/font/Pretendard-Bold.woff
  src/assets/font/Pretendard-Bold.woff2
  src/assets/font/Pretendard-Light.woff
  src/assets/font/Pretendard-Light.woff2
  src/assets/font/Pretendard-Medium.woff
  src/assets/font/Pretendard-Medium.woff2
  src/assets/font/Pretendard-SemiBold.woff
  src/assets/font/Pretendard-SemiBold.woff2
  src/assets/im-404.svg
  src/components/notfound/NotFoundFull.tsx
  src/index.css
Labels: 👌완성

#133 Feat/sidebar design2
  src/assets/icons/IconMenu.tsx
  src/components/common/header/Header.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarETC.tsx
  src/components/common/sideBar/SideBarPlanList.tsx
  src/components/common/sideBar/SideBarStatus.tsx
Labels: 🌸디자인 필요, 🚧진행중

#143 Design/responsive nav
  src/components/common/invite/Invite.tsx
  src/components/common/nav/Nav.tsx
  src/pages/AddPhoto.tsx
  src/pages/AddPlan.tsx
  src/pages/Ending.tsx
Labels: 🖐️merge 필요

#161 Feat/pwa
  public/favicon.ico
  public/images/favicon.ico
  public/images/icon-144x144.png
  public/images/icon-152x152.png
  public/images/icon-256x256.png
  public/images/icon-512x512.png
  public/index.html
  public/manifest.json
  public/offline.html
  src/index.tsx
  src/reportWebVitals.js
Labels: 🚧진행중

#183 Chore: 불필요한 코드 삭제
  public/index.html
Labels: 🚧진행중

#190 Chore: hotfix 이후 dev 최신화
  public/index.html
  public/manifest.json
  src/api/supabaseAuth.ts
Labels: 🔫 트러블슈팅

#193 Refactor/naming button
  src/components/common/confirm/ConfirmModal.tsx
  src/components/common/header/Header.tsx
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/invite/UserList.tsx
  src/components/common/nav/Nav.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarETC.tsx
  src/components/common/sideBar/SideBarPlanList.tsx
  src/index.css
Labels: 👌완성

#197 Fix/name tag
  src/components/addPhoto/endingMap/EndingMap.tsx
  src/components/addPlan/datePage/DatePage.tsx
  src/components/common/footer/Footer.tsx
  src/components/main/bookMark/BookMark.tsx
  src/components/main/card/Card.tsx
  src/pages/AddPhoto.tsx
  src/pages/Ending.tsx
  src/pages/Main.tsx
Labels: 👌완성

#206 Feat/number comma
  src/api/endingData.ts
  src/api/pins.ts
  src/api/plans.ts
  src/components/common/layout/PinLayout.tsx
  src/components/common/pay/EndingPay.tsx
  src/components/common/pay/Pay.tsx
  src/components/ending/totalPay/TotalPay.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/common/MapModalButton.tsx
  src/components/plan/common/MapModalInput.tsx
  src/components/plan/common/MapModalPay.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/hooks/usePlanValidate.ts
  src/pages/AddPhoto.tsx
  src/pages/AddPlan.tsx
  src/pages/Ending.tsx
  src/pages/Plan.tsx
  src/types/supabase.ts
  src/utils/calcDutchPay.ts
Labels: 👌완성

#209 Design: 사이드바 디자인 수정
  src/components/addPlan/calendar/Calendar.tsx
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/layout/PayLayout.tsx
  src/components/common/pay/Pay.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarETC.tsx
  src/pages/Main.tsx
  src/store/sideBarStore.ts
  src/utils/arrayCallbackFunctions.ts
Labels: 👌완성

#217 README.md 최종 업데이트
  README.md
Labels: 👌완성

#224 Dev
  src/api/path.ts
  src/components/ending/placeList/PlaceList.tsx
Labels: 🔫 트러블슈팅

#227 Update README.md
  README.md
Labels: 🖐️merge 필요
