Repository jinoc-git/traduler-project, pull requests merged in 2023-08, with the labels that each got.

#1 Feat: 장소에 대한 지출 등록 로직 구현 완료
  src/components/pay/pay.tsx
  src/pages/Main.tsx
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#2 Feat : 사이드바 여행별 데이터불러오기 기능구현
  src/api/plans.ts
  src/components/common/sideBar/SideBar.tsx
  src/pages/Main.tsx
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#3 Feat/add plan
  src/api/plans.ts
  src/components/plan/PostPlan.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlan.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/store/datesStore.ts
  src/store/pinsStore.ts
  src/store/updatePinStore.ts
Labels: 🌸디자인 필요, 🚧진행중

#4 Feat/profile edit
  craco.config.js
  src/api/supabaseAuth.ts
  src/assets/defaultImg.png
  src/assets/index.ts
  src/components/common/header/Header.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/components/main/profile/Profile.tsx
  src/components/signup/SignUpForm.tsx
  src/hooks/useFormValidator.ts
  src/index.css
  src/pages/Main.tsx
  src/shared/Router.tsx
  src/store/userStore.ts
  src/types/supabase.ts
  src/utils/fileValidator.ts
  src/utils/updateUserProfile.ts
  tsconfig.paths.json
Labels: 🌸디자인 필요

#5 Main컴포넌트에 Card 데이터 불러오기 기능
  src/api/plans.ts
  src/components/common/sideBar/SideBar.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/pages/Main.tsx
  src/shared/Router.tsx
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#6 사진 업로드 기능 구현
  package.json
  src/api/picture.ts
  src/api/supabaseAuth.ts
  src/api/supabasePlans.ts
  src/components/addpicture/AddPicture.tsx
  src/pages/AddPhoto.tsx
  src/shared/Router.tsx
  src/types/supabase.ts
  yarn.lock
Labels: 👌완성, 🌸디자인 필요, 🖐️merge 필요

#7 Ending 페이지 total cost 구현
  src/api/plans.ts
  src/components/pay/AddPay.tsx
  src/components/pay/TotalPay.tsx
  src/components/pay/pay.tsx
  src/components/plan/addPlan/AddPlan.tsx
  src/pages/Ending.tsx
  src/shared/Router.tsx
Labels: 🌸디자인 필요, 🖐️merge 필요

#8 Feat/update plan
  package.json
  src/api/pins.ts
  src/api/plans.ts
  src/components/plan/Calendar.tsx
  src/components/plan/PostPlan.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlan.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/map.ts
  src/components/plan/updatePlan/Map.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/Plan.tsx
  src/shared/Router.tsx
  src/store/pinsStore.ts
  tsconfig.json
  yarn.lock
Labels: 🚧진행중, 🖐️merge 필요

#9 Feat/google login
  src/api/supabaseAuth.ts
  src/assets/bx_password.svg
  src/assets/clarity_email-solid.svg
  src/components/common/header/Header.tsx
  src/components/signin/SignInForm.tsx
  src/components/signup/SignUpForm.tsx
  src/store/userStore.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#10 Feat/404page
  src/components/404/NotFoundFull.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/NotFound.tsx
  src/shared/Router.tsx
Labels: 👌완성, 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#11 Feat/sign with google
  src/api/supabaseAuth.ts
  src/components/common/header/Header.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/pages/AuthLoading.tsx
  src/shared/Router.tsx
  src/store/userStore.ts
  src/types/supabase.ts
  src/utils/updateUserProfile.ts
Labels: 👌완성

#13 Feat: 회원가입 닉네임, 이메일 중복 체크 추가
  src/api/supabaseAuth.ts
  src/components/main/profile/Profile.tsx
  src/components/signup/SignUpForm.tsx
  src/hooks/useBooleanState.ts
Labels: 🌸디자인 필요

#14 Feat: sidebar 기능 추가
  src/components/404/NotFoundFull.tsx
  src/components/common/header/Header.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/plan/listingPlan/Card.tsx
  src/pages/Main.tsx
  src/shared/Router.tsx
  src/store/sidebarStore.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#15 Feat/distanceData
  src/api/path.ts
  src/api/pins.ts
  src/components/plan/PostPlan.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlan.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/components/plan/updatePlan/Pins.tsx
Labels: 🌸디자인 필요, 🖐️merge 필요

#16 Feat/add plan modal
  package.json
  src/api/pins.ts
  src/api/plans.ts
  src/api/users.ts
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/nav/Nav.tsx
  src/components/plan/PostPlan.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlan.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/AddPlan.tsx
  src/pages/Plan.tsx
  src/shared/Router.tsx
  src/store/datesStore.ts
  src/store/inviteUserStore.ts
  src/types/supabase.ts
  tailwind.config.js
  yarn.lock
Labels: 🖐️merge 필요

#17 Feat/header profile
  src/components/404/NotFoundFull.tsx
  src/components/common/header/Header.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/components/main/profile/Profile.tsx
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/components/signin/SignInForm.tsx
  src/pages/Main.tsx
  src/pages/Plan.tsx
  src/store/sidebarStore.ts
Labels: 🌸디자인 필요, 🚧진행중

#18 Fix: file name
  src/components/addpicture/AddPicture.tsx
  src/components/pay/Pay.tsx
  src/store/sideBarStore.ts
Labels: 🖐️merge 필요

#19 Fix : plan 페이지 pin결과 없을 시 오류 수정, 친구초대 시 currentUser 포함
  src/api/planMates.ts
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/plan/Calendar.tsx
  src/components/plan/PostPlan.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/AddPlan.tsx
  src/pages/Plan.tsx
  src/types/supabase.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#20 Feat: 지출 input addPlan, Plan page 불러오기
  src/components/plan/addPlan/AddMapModal.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/updatePlan/MapModal.tsx
  src/components/plan/updatePlan/Pins.tsx
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#21 Feat/invite user
  src/api/planMates.ts
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/invite/UserList.tsx
  src/components/plan/Calendar.tsx
  src/pages/Plan.tsx
  src/store/inviteUserStore.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#22 Feat/list favorites
  src/api/plans.ts
  src/components/addpicture/AddPicture.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/main/favorite/Favorite.tsx
  src/components/plan/Calendar.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/pages/AuthLoading.tsx
  src/types/supabase.ts
Labels: 🚧진행중

#23 Feat/sidebar
  src/api/plans.ts
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/utils/changeFormatDay.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#24 Feat/total dates pay
  src/api/datesPay.ts
  src/api/path.ts
  src/components/plan/Calendar.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/pages/Ending.tsx
  src/shared/Router.tsx
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#25 Feat/drag drop
  package.json
  src/api/path.ts
  src/api/supabaseAuth.ts
  src/assets/defaultImg.png
  src/assets/icons/IconGridDefault.tsx
  src/assets/icons/IconMicroMenu.tsx
  src/assets/icons/IconPin.tsx
  src/assets/icons/IconSixDots.tsx
  src/assets/index.ts
  src/assets/user-profile-default-black-100x100.png
  src/assets/user-profile-default-gray-100x100.png
  src/components/common/header/Header.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/main/profile/EditProfileModal.tsx
  src/components/main/profile/Profile.tsx
  src/components/plan/Calendar.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/updatePlan/DropDown.tsx
  src/components/plan/updatePlan/Pin.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/index.css
  src/types/icon.ts
  tailwind.config.js
  yarn.lock
Labels: 🌸디자인 필요, 🚧진행중

#26 Feat/invite user
  src/api/plans.ts
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/invite/UserList.tsx
  src/components/plan/PostPlan.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/AddPlan.tsx
  src/pages/Plan.tsx
  src/store/datesStore.ts
  src/store/inviteUserStore.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#27 Feat/drag drop 2
  package.json
  src/assets/btn-logout-dropdown-w-contents.png
  src/assets/index.ts
  src/components/common/header/Header.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/updatePlan/Pin.tsx
  src/components/plan/updatePlan/Pins.tsx
  yarn.lock
Labels: 🌸디자인 필요, 🪳버그, 🚧진행중

#29 Feat/insert dates
  src/api/endingData.ts
  src/api/path.ts
  src/components/plan/updatePlan/Pins.tsx
  src/pages/AddPhoto.tsx
  src/shared/Router.tsx
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#31 Feat/main favorite
  src/api/bookMarks.ts
  src/api/plans.ts
  src/components/common/sideBar/SideBar.tsx
  src/components/main/favorite/Favorite.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/types/supabase.ts
Labels: 🚧진행중

#32 Feat/ending comment
  src/api/commets.ts
  src/api/plans.ts
  src/components/comments/Comments.tsx
  src/components/common/invite/Invite.tsx
  src/components/common/invite/SearchPeople.tsx
  src/components/common/invite/UserList.tsx
  src/components/main/favorite/Favorite.tsx
  src/components/plan/addPlan/AddPlanContents.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
  src/components/plan/updatePlan/UpdatePlan.tsx
  src/pages/AddPlan.tsx
  src/pages/Plan.tsx
  src/types/supabase.ts
Labels: 🌸디자인 필요, 🚧진행중, 🖐️merge 필요

#34 Feat/favorite optimitic
  src/api/bookMarks.ts
  src/api/plans.ts
  src/assets/icons/IconFavoriteDefault.tsx
  src/assets/icons/IconFavoriteSolid.tsx
  src/components/main/favorite/Favorite.tsx
  src/components/plan/listingPlan/Card.tsx
  src/components/plan/listingPlan/CardSection.tsx
Labels: 👌완성, 🖐️merge 필요

#36 Feat/plan state change
  src/api/plans.ts
  src/components/plan/Calendar.tsx
  src/components/plan/updatePlan/Pins.tsx
  src/pages/AddPlan.tsx
  src/pages/Plan.tsx
Labels: 🖐️merge 필요

#37 Feat/insert ending info
  src/api/endingData.ts
  src/api/path.ts
  src/api/picture.ts
  src/pages/AddPhoto.tsx
  src/types/supabase.ts
Labels: 🌸디자인 필요, 🖐️merge 필요
